services:
  db:
    image: mysql:8.0
    container_name: ap-mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT}:8080"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ap-frontend
    # Serve on http://localhost:3000
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend

  adminer:
    image: adminer:latest
    container_name: ap-adminer
    depends_on:
      - db
    ports:
      - "${ADMINER_PORT}:8080"
    # Visit http://localhost:${ADMINER_PORT}
    # Server: db | Username: root | Password: MYSQL_ROOT_PASSWORD | DB: adventure_db

volumes:
  mysql_data: